name: Ceph S3 Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        default: RCS stage
        type: environment
        required: true

jobs:
  e2e_tests:
    name: e2e Tests
    environment: ${{ inputs.environment || 'RCS stage' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install tox

      - name: Update config file
        run: |
          sed -i "s|<host>|${{ vars.HOST }}|" s3tests.conf
          sed -i "s|<main_access_key>|${{ vars.MAIN_ACCESS_KEY }}|" s3tests.conf
          sed -i "s|<main_secret_key>|${{ secrets.MAIN_SECRET_KEY }}|" s3tests.conf
          sed -i "s|<alt_access_key>|${{ vars.ALT_ACCESS_KEY }}|" s3tests.conf
          sed -i "s|<alt_secret_key>|${{ secrets.ALT_SECRET_KEY }}|" s3tests.conf

      - name: Test
        env:
          S3TEST_CONF: s3tests.conf
          S3_USE_SIGV4: true
          PY_COLORS: 1
        run: tox
